### ISSUE TITLE
make setup fails - Cannot build local copy of the book

### ISSUE THREAD

**Issue by iprog4u** [lfe/sicp#19]
make deps works however I am unable to make setup and therefore the local copy of the Gitbook.  What am I missing?

Core i3 on Netrunner which is based off of Arch Linux.

Output:

> sudo make setup
Installing GitBook 2.6.7
gitbook@2.6.7 ../../../../../tmp/tmp-92836sPbG9rjERle/node_modules/gitbook
├── bash-color@0.0.3
├── escape-string-regexp@1.0.3
├── nunjucks-filter@1.0.0
├── gitbook-plugin-livereload@0.0.1
├── gitbook-plugin-sharing@1.0.1
├── gitbook-plugin-fontsettings@1.0.2
├── github-slugid@1.0.0
├── nunjucks-autoescape@1.0.0
├── jsonschema@1.0.2
├── spawn-cmd@0.0.2
├── q@1.0.1
├── json-schema-defaults@0.1.1
├── graceful-fs@3.0.5
├── semver@5.0.1
├── urijs@1.17.0
├── crc@3.2.1
├── tmp@0.0.24
├── dom-serializer@0.1.0 (domelementtype@1.1.3, entities@1.1.1)
├── npmi@0.1.1 (semver@4.3.6)
├── merge-defaults@0.2.1 (lodash@2.4.2)
├── resolve@0.6.3
├── send@0.2.0 (fresh@0.2.4, range-parser@1.0.3, mime@1.2.11, debug@2.6.8)
├── i18n@0.5.0 (sprintf@0.1.5, mustache@2.3.0, debug@2.6.8)
├── fs-extra@0.16.5 (jsonfile@2.4.0, rimraf@2.6.1)
├── request@2.51.0 (tunnel-agent@0.4.3, aws-sign2@0.5.0, forever-agent@0.5.2, caseless@0.8.0, oauth-sign@0.5.0, stringstream@0.0.5, json-stringify-safe@5.0.1, mime-types@1.0.2, qs@2.3.3, node-uuid@1.4.8, tough-cookie@2.3.2, combined-stream@0.0.7, http-signature@0.10.1, bl@0.9.5, form-data@0.2.0, hawk@1.1.1)
├── nunjucks@2.2.0 (asap@2.0.6, optimist@0.6.1)
├── tiny-lr@0.2.1 (parseurl@1.3.1, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── fstream-ignore@1.0.2 (inherits@2.0.3, minimatch@2.0.10, fstream@1.0.11)
├── gitbook-plugin-search@1.1.0 (lunr@0.5.12)
├── cheerio@0.19.0 (entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3)
├── chokidar@1.0.6 (path-is-absolute@1.0.1, arrify@1.0.1, is-glob@1.1.3, async-each@0.1.6, is-binary-path@1.0.1, glob-parent@1.3.0, readdirp@1.4.0, anymatch@1.3.0)
├── gitbook-parsers@0.8.9 (q@1.5.0, gitbook-restructuredtext@0.2.3, gitbook-markdown@0.5.3, gitbook-asciidoc@0.2.4)
├── gitbook-plugin-highlight@1.0.3 (highlight.js@8.8.0)
├── lodash@3.10.1
├── juice@1.5.0 (commander@2.3.0, slick@1.12.1, batch@0.5.2, cssom@0.3.0, web-resource-inliner@1.1.4)
└── npm@2.4.1
Error loading version latest: Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/root/.gitbook/versions/2.6.7/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

TypeError: Cannot read property 'commands' of null
make: *** [Makefile:15: setup] Error 1
yanosh@lappy ~/s/l/sicp> sudo make book
gitbook build ./ --output=_book
Error loading version latest: Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/root/.gitbook/versions/2.6.7/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

TypeError: Cannot read property 'commands' of null

**Comment by oubiwann** [comment]
Hrm. It's been a while since I built SICP on command line; I usually had Gitbook do that remotely (on their servers). Looking at the stacktrace, it's an issue with the node libs ... quite possibly the commands used in the `Makefile` could no longer be supported in the latest version of Gitbook. I'll look into this more.

**Comment by iprog4u** [comment]
Thank you Duncan.  I'd fix it myself if I weren't so new to Erlang (just
finished error handling in LYSE book).  The SICP book has chapters online
in the meanwhile.  Thanks again for replying.

David Bloom


On Jul 24, 2017 9:05 AM, "Duncan McGreggor" <notifications@github.com>
wrote:

Hrm. It's been a while since I built SICP on command line; I usually had
Gitbook do that remotely (on their servers). Looking at the stacktrace,
it's an issue with the node libs ... quite possibly the commands used in
the Makefile could no longer be supported in the latest version of Gitbook.
I'll look into this more.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lfe/sicp/issues/19#issuecomment-317416113>, or mute the
thread

**Comment by oubiwann** [comment]
Just in case you're still interested, it's much easier to build locally -- check out the README for the latest :-)
