### ISSUE TITLE
contributing to this repo

### ISSUE THREAD

**Issue by minostro** [lfe/sicp#23]
I would like to start contributing to this repo. I am currently working as a software engineer, and I have computer science background. Is there any plan on how to contribute to the document?
 any guidelines or plans?

**Comment by oubiwann** [comment]
Hey @minostro, seems that I haven't been getting notifications from this repo ... 3 years late :-( 

It's much easier to contribute now, should you still be interested (or regain an old, lost interest 😉). Check out the `README.md` for more info ...

**Comment by minostro** [comment]
I will check it out. Thanks @oubiwann
