### ISSUE TITLE
LaTeX formulas not formatted

### ISSUE THREAD

**Issue by lambdam** [lfe/sicp#26]
Hello,

I'm reading the LFE SICP book compiled with the mdbook binary and the LaTeX formulas are displayed as a source, not the compiled LaTeX output.

![Screenshot_20230108_145433](https://user-images.githubusercontent.com/1669165/211199953-c1879882-f449-4cfd-b504-7bc9f464557b.png)

Thanks for all the great work on LFE

----

Additional ticket edits from @oubiwann:

* [x] 2.2.4 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.2.6 - Fix case LaTeX block (will probably have to drop equation numbering)
* [x] 2.2.6 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.2.8 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.2.9 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.1 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.2 - The Ackermann function's LaTeX has gotten hosed; fix according to examples here: https://en.wikipedia.org/wiki/Ackermann_function
* [x] 2.3.3 - Fib LaTeX cases statement is broken; fix to make cases in original SICP
* [x] 2.3.3 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.4 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.4 - Fix LaTeX for Pascal's Triangle
* [x] 2.3.5 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.6 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.7 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.8 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.9 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.9 - Fix layout of successive GCD calls
* [x] 2.3.11 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.3.12 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.1 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.2 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.3 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.5 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.6 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.7 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.8 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 2.4.8 - Fix the text that got moved into LaTeX
* [x] 3 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.1.1 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.1.4 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.1.6 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.1.8 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.2.1.1 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.2.3 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.2.3.1 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.2.3.2 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.2.3.3 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines
* [x] 3.2.3.4 - Inline LaTeX has been changed to render as blocks, oddly splitting text over many lines

**Comment by ghost** [comment]
Hi @lambdam,

I was able to solve this issue using [mdbook-katex](https://github.com/lzanini/mdbook-katex).

Just make sure you have that in path and add

```
[preprocessor.katex]
after = ["links"]
```

to the `book.toml`

**Comment by oubiwann** [comment]
Yeah, prior to mdbook, we used another LaTeX solution for use in HTML pages. mdbook supports MathJax, but not the `$$` syntax. Furthermore, I've just found a bunch more LaTeX rendering issues ... I'll document these and start working through them.

**Comment by oubiwann** [comment]
Btw, most of the fixes involve just changing block `$$` declarations to `\\[` ... `\\]` and changing `$$` inline declarations to `\\(` ... `\\)`. There is the occasional failure of complex LaTeX, and I've been fixing those as I come across them, too.

**Comment by oubiwann** [comment]
Making some good progress ... about 1/3 through the punch list :-D

**Comment by oubiwann** [comment]
HOLY CRAP.

Done.

Gonna close this puppy :-) Feel free to re-open or file a new one if you find any remaining bad LaTeX rendering!
