### ISSUE TITLE
Question: can I buy a phisycal version of this book? Or, can I convert it to epub or pdf?

### ISSUE THREAD

**Issue by ghost** [lfe/sicp#28]
Hi all,

1. Is it possible to buy a phisycal version of the book?
2. If not, is it possible to build an epub (or pdf) version of it, so I can use an
    online service to print it? 

Regarding [2] I tried both [mdbook-pdf](https://github.com/HollowMan6/mdbook-pdf) and
[mdbook-epub](https://github.com/Michael-F-Bryan/mdbook-epub) with no success.

Both commands just hangs forever.

Thank you!

**Comment by oubiwann** [comment]
Ah, I see I've caught up to you 😆 

Yes, as you know if you've checked Discord, I've confirmed your observation about mdbook-pdf 😉 

I did get mdbook-epub to work, but it has many rendering issues.

I've also tried mdbook-typest, and it has its own issues, though it does actually generate a PDF file (I've committed and pushed this change in `book.toml`).

I could not even get mdbook-latex to install 😭 ...

**Comment by ghost** [comment]
@oubiwann 

I built different PDFs with both mdbook-typest and mdbook-pandoc [1] which supports different pdf engines.

I am happy since I can read them easily enough on my ebook reader.

Got not luck with epub unfortunately, that would be fantastic. 

[1] https://github.com/max-heller/mdbook-pandoc
