### ISSUE TITLE
Use of chapter numbering

### ISSUE THREAD

**Issue by nelmil** [lfe/sicp#3]
In the book you start with chapter 10 and is non traditional. For example, in 10.2.3 Evaluating Combinations you mention chapter 11 which I presume is Chapter 1 for SICP. This is confusing. Is it possible to stick to the original SICP chapters and move 1-9 to an introduction/preface chapter?

**Comment by oubiwann** [comment]
Yeah. _sighs_ (I have the same, rather intense, issue with this)

This is a Gitbook issue. There's currently no way (that I know of) where authors can override the default numbering that is used by Gitbook. In particular, 1) Gitbook uses the `SUMMARY.md` file to generate ToC, and 2) the `SUMMARY.md` file is very rigid (some might say "brittle").

That being said, they are continually adding new features, so perhaps we'll get some control over this before the end of the book ... I think it'd actually like to _disable_ number of chapter and sections altogether. This would then give me the freedom to simply preface each chapter with "Chapter X: ..."

**Comment by oubiwann** [comment]
I think I'm going to give your suggestion a try and see how it feels: put all the front matter into its own sub-section ... it's just so ridiculous with all these numbers :-/

**Comment by oubiwann** [comment]
Hey! Look at that!

I buried the front matter under the README.md ("Introduction"), and this bumped the chapters to their proper numbers. Thanks for creating this ticket ... I might have just suffered with the bad numbers if you hadn't spoken up :-)
