### ISSUE TITLE
Exercise 1.1

### ISSUE THREAD

**Issue by shrogers** [lfe/sicp#7]
(= a b) 
should be 
(== a b)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(cond ((= a 4) 6)
      ((= b 4) (+ 6 7 a))
      (else 25))

should be

(cond ((== a 4) 6)
      ((== b 4) (+ 6 7 a))
      (else 25))

**Comment by oubiwann** [comment]
Been meaning to respond to your recent contributions for a few days now --
thanks!

I've added the issues you've been catching to my TODO list :-D

**Comment by shrogers** [comment]
You're welcome.  I appreciate the work you're doing and am enjoying LFE.
I've played with Erlang and Lisp in the past but mostly worked in
C/C++/Java/Python.

On Wed, Apr 22, 2015 at 11:18 AM, Duncan McGreggor <notifications@github.com

> wrote:
> 
> Been meaning to respond to your recent contributions for a few days now --
> thanks!
> 
> I've added the issues you've been catching to my TODO list :-D
> 
> On Sat, Apr 18, 2015 at 8:30 PM, Steve Rogers notifications@github.com
> wrote:
> 
> > (= a b)
> > should be
> > (== a b)
> > 
> > ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> > 
> > (cond ((= a 4) 6)
> > ((= b 4) (+ 6 7 a))
> > (else 25))
> > 
> > should be
> > 
> > (cond ((== a 4) 6)
> > ((== b 4) (+ 6 7 a))
> > (else 25))
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/lfe/sicp/issues/7.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lfe/sicp/issues/7#issuecomment-95270987.

## 

Steve Rogers
http://www.linkedin.com/in/shrogers
“"Don't worry about what anybody else is going to do… The best way to
predict the _future_ is to _invent_ it."\* -*- Alan Kay

**Comment by oubiwann** [comment]
I'm _finally_ getting around to this! Just fixed it -- thanks again :-)
